"""ASS subtitle generation.

Real ASS, not SRT with a ``force_style`` override. The difference matters:

* ``PlayResX``/``PlayResY`` are set to the actual output canvas, so a font size
  means the same thing at 1080p and at 4K. Upstream's sizes are relative to
  libass's default 288-line virtual canvas, so the same number produces
  different captions at different resolutions.
* Per-cue positioning, per-speaker colours, and active-word highlighting are
  expressible. With ``force_style`` they are not.
"""

from __future__ import annotations

from pathlib import Path

from social_video.captions.emphasis import emphasis_keys, is_emphasised
from social_video.schemas.brand import CaptionPosition, CaptionStyle
from social_video.schemas.captions import CaptionTrack

#: ASS numpad alignment values.
_ALIGNMENT = {
    CaptionPosition.BOTTOM: 2,
    CaptionPosition.LOWER_THIRD: 2,
    CaptionPosition.LOWER_SAFE_ZONE: 2,
    CaptionPosition.CENTER: 5,
    CaptionPosition.TOP: 8,
}


def hex_to_ass_colour(value: str, alpha: int = 0) -> str:
    """Convert ``#RRGGBB`` to ASS ``&HAABBGGRR``.

    ASS stores colour channels in reverse order and prefixes an alpha byte where
    0 is fully opaque. Both are easy to get backwards.
    """
    text = value.lstrip("#").strip()
    if len(text) == 8:  # #RRGGBBAA
        rr, gg, bb, aa = text[0:2], text[2:4], text[4:6], text[6:8]
        alpha = 255 - int(aa, 16)
    elif len(text) == 6:
        rr, gg, bb = text[0:2], text[2:4], text[4:6]
    elif len(text) == 3:
        rr, gg, bb = text[0] * 2, text[1] * 2, text[2] * 2
    else:
        raise ValueError(f"colour must be #RGB, #RRGGBB or #RRGGBBAA, got {value!r}")
    return f"&H{alpha:02X}{bb.upper()}{gg.upper()}{rr.upper()}"


def format_timestamp(seconds: float) -> str:
    """ASS timestamps are ``H:MM:SS.cc`` with exactly two decimal places."""
    seconds = max(0.0, seconds)
    hours, rest = divmod(seconds, 3600)
    minutes, secs = divmod(rest, 60)
    return f"{int(hours)}:{int(minutes):02d}:{secs:05.2f}"


def escape_text(text: str) -> str:
    """Escape ASS dialogue text.

    A literal backslash or brace would otherwise be read as an override tag.
    """
    return text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}").replace("\n", "\\N")


def render_ass(
    track: CaptionTrack,
    style: CaptionStyle,
    *,
    width: int,
    height: int,
    font_name: str | None = None,
) -> str:
    """Render a caption track as an ASS document."""
    family = font_name or style.font_family or "Sans"
    font_size = max(8, round(height * style.font_size_pct / 100.0))
    margin_v = round(height * style.margin_pct / 100.0)
    margin_h = round(width * 0.06)
    alignment = _ALIGNMENT[style.position]
    if style.position is CaptionPosition.LOWER_THIRD:
        margin_v = round(height * max(style.margin_pct, 22.0) / 100.0)

    # BorderStyle 3 draws an opaque box behind the text; 1 draws an outline.
    border_style = 3 if style.background_box or style.background_style.value != "none" else 1

    lines = [
        "[Script Info]",
        "; Generated by social-video-agent",
        "ScriptType: v4.00+",
        f"PlayResX: {width}",
        f"PlayResY: {height}",
        # 0 = smart wrapping with balanced lines. WrapStyle 2 disables wrapping
        # entirely, which lets a long cue run off both edges of the frame.
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    ]

    def style_line(name: str, primary: str) -> str:
        return (
            f"Style: {name},{family},{font_size},"
            f"{hex_to_ass_colour(primary)},"
            f"{hex_to_ass_colour(style.highlight_colour)},"
            f"{hex_to_ass_colour(style.outline_colour)},"
            f"{hex_to_ass_colour(style.background_colour)},"
            f"{-1 if style.bold else 0},0,0,0,100,100,0,0,"
            f"{border_style},{style.outline_width:g},{style.shadow:g},{alignment},"
            f"{margin_h},{margin_h},{margin_v},1"
        )

    lines.append(style_line("Default", style.primary_colour))
    for speaker, colour in sorted(style.speaker_colours.items()):
        lines.append(style_line(_speaker_style(speaker), colour))

    lines += [
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    keys = emphasis_keys(style.emphasis_words)
    for cue in sorted(track.cues, key=lambda c: c.start):
        speaker_colour = style.speaker_colours.get(cue.speaker) if cue.speaker else None
        name = _speaker_style(cue.speaker) if speaker_colour else "Default"
        base = speaker_colour or style.primary_colour
        if style.highlight_active_word and cue.words:
            text = _active_word(cue, style, base=base, keys=keys)
        elif keys:
            text = _emphasised(cue.text, style, base=base, keys=keys)
        else:
            text = escape_text(cue.text)
        lines.append(
            f"Dialogue: 0,{format_timestamp(cue.start)},{format_timestamp(cue.end)},"
            f"{name},,0,0,0,,{text}"
        )

    return "\n".join(lines) + "\n"


def _emphasised(text: str, style: CaptionStyle, *, base: str, keys: frozenset[str]) -> str:
    """Recolour brand keywords inside an already-cased cue, word by word."""
    plain = hex_to_ass_colour(base)
    emphasis = hex_to_ass_colour(style.emphasis_colour)
    return " ".join(
        f"{{\\1c{emphasis}}}{escape_text(word)}{{\\1c{plain}}}"
        if is_emphasised(word, keys)
        else escape_text(word)
        for word in text.split(" ")
    )


def _active_word(cue, style: CaptionStyle, *, base: str, keys: frozenset[str] = frozenset()) -> str:
    """Colour only the word being spoken, exactly while it is spoken.

    Each word starts in the cue's colour, switches to the highlight colour when
    it begins and back when it ends, using near-instant ``\\t`` transforms
    timed from the start of the line. This matches what the Remotion
    compositor draws. ASS karaoke (``\\k``/``\\kf``) is deliberately not used:
    it paints every word not yet spoken in the highlight colour and leaves the
    spoken ones plain, which is the opposite of an active-word highlight.

    The style's case is applied here too. This path renders the individual
    words rather than the cue's already-cased text, so without doing so an
    uppercase caption style would silently render as spoken whenever
    highlighting was enabled.
    """
    from social_video.captions.chunk import apply_case

    active = hex_to_ass_colour(style.highlight_colour)
    parts: list[str] = []
    for word in cue.words:
        # A brand keyword rests in its emphasis colour and is still
        # highlighted while spoken, like every other word.
        plain = hex_to_ass_colour(style.emphasis_colour if is_emphasised(word.text, keys) else base)
        begin = max(0, round((word.start - cue.start) * 1000))
        end = max(begin + 10, round((word.end - cue.start) * 1000))
        text = escape_text(apply_case(word.text, style.case))
        # libass ignores a transform whose start and end are equal, so each
        # switch takes one millisecond rather than none.
        parts.append(
            f"{{\\1c{plain}\\t({begin},{begin + 1},\\1c{active})"
            f"\\t({end},{end + 1},\\1c{plain})}}{text}"
        )
    return " ".join(parts)


def _speaker_style(speaker: str | None) -> str:
    """ASS style names may not contain commas."""
    return "S_" + (speaker or "unknown").replace(",", "_").replace(" ", "_")


def write_ass(
    track: CaptionTrack,
    style: CaptionStyle,
    path: Path,
    *,
    width: int,
    height: int,
    font_name: str | None = None,
) -> Path:
    """Write an ASS file as UTF-8, which is the only encoding libass accepts."""
    path.parent.mkdir(parents=True, exist_ok=True)
    document = render_ass(track, style, width=width, height=height, font_name=font_name)
    path.write_text(document, encoding="utf-8")
    return path


#: A cubic Bezier quarter circle: control points sit this fraction of the
#: radius from the corner's ends.
_KAPPA = 0.5523


def _rounded_rect(width: float, height: float, radius: float) -> str:
    """An ASS drawing of a rounded rectangle whose top-left corner is the origin."""
    w, h = round(width), round(height)
    r = max(0, min(round(radius), w // 2, h // 2))
    c = round(r * (1 - _KAPPA))
    if r == 0:
        return f"m 0 0 l {w} 0 l {w} {h} l 0 {h}"
    return (
        f"m {r} 0 l {w - r} 0 b {w - c} 0 {w} {c} {w} {r} "
        f"l {w} {h - r} b {w} {h - c} {w - c} {h} {w - r} {h} "
        f"l {r} {h} b {c} {h} 0 {h - c} 0 {h - r} "
        f"l 0 {r} b 0 {c} {c} 0 {r} 0"
    )


def render_boxed_ass(
    track: CaptionTrack,
    style: CaptionStyle,
    layout,
    *,
    width: int,
    height: int,
    safe_margins: dict[str, float] | None = None,
    font_name: str | None = None,
) -> str:
    """Captions on a rounded box, drawn by libass from the measured layout.

    The same geometry the Remotion compositor draws: the measured lines, the
    per-cue size, the layout's padding and line height, and the contract's
    corner radius. The box is a vector drawing on layer 0 and each line of text
    is placed on layer 1 at its own computed position, so libass never wraps
    or spaces anything itself.
    """
    margins = safe_margins or {}
    left = width * float(margins.get("left", 6.0)) / 100
    right = width * float(margins.get("right", 6.0)) / 100
    centre_x = left + (width - left - right) / 2
    family = font_name or style.font_family or "Sans"
    background = hex_to_ass_colour(style.background_colour)
    keys = emphasis_keys(style.emphasis_words)
    by_index = {cue.index: cue for cue in layout.cues}
    lines = [
        "[Script Info]",
        "; Generated by social-video-agent (rounded caption box)",
        "ScriptType: v4.00+",
        f"PlayResX: {width}",
        f"PlayResY: {height}",
        # Every line is placed explicitly; libass must not wrap any of them.
        "WrapStyle: 2",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{family},{layout.requested_font_size_px},"
        f"{hex_to_ass_colour(style.primary_colour)},{hex_to_ass_colour(style.highlight_colour)},"
        f"{hex_to_ass_colour(style.outline_colour)},{background},"
        f"{-1 if style.bold else 0},0,0,0,100,100,0,0,1,"
        f"{style.outline_width:g},{style.shadow:g},8,0,0,0,1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    for cue in sorted(track.cues, key=lambda c: c.start):
        drawn = by_index.get(cue.index)
        if drawn is None:
            continue
        line_px = drawn.font_size_px * layout.line_height
        box_w = drawn.max_line_width_px + 2 * layout.padding_x
        box_h = len(drawn.lines) * line_px + layout.padding_top + layout.padding_bottom
        margin = height * style.margin_pct / 100
        if style.position is CaptionPosition.TOP:
            top = margin
        elif style.position is CaptionPosition.CENTER:
            top = (height - box_h) / 2
        else:
            top = height - margin - box_h
        start, end = format_timestamp(cue.start), format_timestamp(cue.end)
        x0 = centre_x - box_w / 2
        lines.append(
            f"Dialogue: 0,{start},{end},Default,,0,0,0,,"
            f"{{\\an7\\pos({round(x0)},{round(top)})\\p1\\bord0\\shad0"
            f"\\1c{background}\\1a&H00&}}{_rounded_rect(box_w, box_h, style.corner_radius)}"
        )
        speaker_colour = style.speaker_colours.get(cue.speaker) if cue.speaker else None
        base = speaker_colour or style.primary_colour
        for number, line in enumerate(drawn.lines):
            y = top + layout.padding_top + number * line_px
            if style.highlight_active_word and line.words:
                text = _active_word(
                    _LineCue(start=cue.start, words=list(line.words)), style, base=base, keys=keys
                )
            elif keys:
                text = _emphasised(line.text, style, base=base, keys=keys)
            else:
                text = escape_text(line.text)
            lines.append(
                f"Dialogue: 1,{start},{end},Default,,0,0,0,,"
                f"{{\\an8\\pos({round(centre_x)},{round(y)})\\fs{drawn.font_size_px}"
                f"\\1c{hex_to_ass_colour(base)}}}{text}"
            )
    return "\n".join(lines) + "\n"


class _LineCue:
    """The slice of a cue one drawn line needs for word timing."""

    def __init__(self, *, start: float, words: list) -> None:
        self.start = start
        self.words = words
