"""ASS subtitle generation.

Real ASS, not SRT with a ``force_style`` override. The difference matters:

* ``PlayResX``/``PlayResY`` are set to the actual output canvas, so a font size
  means the same thing at 1080p and at 4K. Upstream's sizes are relative to
  libass's default 288-line virtual canvas, so the same number produces
  different captions at different resolutions.
* Per-cue positioning, per-speaker colours, and active-word highlighting are
  expressible. With ``force_style`` they are not.
"""

from __future__ import annotations

from pathlib import Path

from social_video.schemas.brand import CaptionPosition, CaptionStyle
from social_video.schemas.captions import CaptionTrack

#: ASS numpad alignment values.
_ALIGNMENT = {
    CaptionPosition.BOTTOM: 2,
    CaptionPosition.LOWER_THIRD: 2,
    CaptionPosition.LOWER_SAFE_ZONE: 2,
    CaptionPosition.CENTER: 5,
    CaptionPosition.TOP: 8,
}


def hex_to_ass_colour(value: str, alpha: int = 0) -> str:
    """Convert ``#RRGGBB`` to ASS ``&HAABBGGRR``.

    ASS stores colour channels in reverse order and prefixes an alpha byte where
    0 is fully opaque. Both are easy to get backwards.
    """
    text = value.lstrip("#").strip()
    if len(text) == 8:  # #RRGGBBAA
        rr, gg, bb, aa = text[0:2], text[2:4], text[4:6], text[6:8]
        alpha = 255 - int(aa, 16)
    elif len(text) == 6:
        rr, gg, bb = text[0:2], text[2:4], text[4:6]
    elif len(text) == 3:
        rr, gg, bb = text[0] * 2, text[1] * 2, text[2] * 2
    else:
        raise ValueError(f"colour must be #RGB, #RRGGBB or #RRGGBBAA, got {value!r}")
    return f"&H{alpha:02X}{bb.upper()}{gg.upper()}{rr.upper()}"


def format_timestamp(seconds: float) -> str:
    """ASS timestamps are ``H:MM:SS.cc`` with exactly two decimal places."""
    seconds = max(0.0, seconds)
    hours, rest = divmod(seconds, 3600)
    minutes, secs = divmod(rest, 60)
    return f"{int(hours)}:{int(minutes):02d}:{secs:05.2f}"


def escape_text(text: str) -> str:
    """Escape ASS dialogue text.

    A literal backslash or brace would otherwise be read as an override tag.
    """
    return text.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}").replace("\n", "\\N")


def render_ass(
    track: CaptionTrack,
    style: CaptionStyle,
    *,
    width: int,
    height: int,
    font_name: str | None = None,
) -> str:
    """Render a caption track as an ASS document."""
    family = font_name or style.font_family or "Sans"
    font_size = max(8, round(height * style.font_size_pct / 100.0))
    margin_v = round(height * style.margin_pct / 100.0)
    margin_h = round(width * 0.06)
    alignment = _ALIGNMENT[style.position]
    if style.position is CaptionPosition.LOWER_THIRD:
        margin_v = round(height * max(style.margin_pct, 22.0) / 100.0)

    # BorderStyle 3 draws an opaque box behind the text; 1 draws an outline.
    border_style = 3 if style.background_box or style.background_style.value != "none" else 1

    lines = [
        "[Script Info]",
        "; Generated by social-video-agent",
        "ScriptType: v4.00+",
        f"PlayResX: {width}",
        f"PlayResY: {height}",
        # 0 = smart wrapping with balanced lines. WrapStyle 2 disables wrapping
        # entirely, which lets a long cue run off both edges of the frame.
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "YCbCr Matrix: TV.709",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
        "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
        "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
    ]

    def style_line(name: str, primary: str) -> str:
        return (
            f"Style: {name},{family},{font_size},"
            f"{hex_to_ass_colour(primary)},"
            f"{hex_to_ass_colour(style.highlight_colour)},"
            f"{hex_to_ass_colour(style.outline_colour)},"
            f"{hex_to_ass_colour(style.background_colour)},"
            f"{-1 if style.bold else 0},0,0,0,100,100,0,0,"
            f"{border_style},{style.outline_width:g},{style.shadow:g},{alignment},"
            f"{margin_h},{margin_h},{margin_v},1"
        )

    lines.append(style_line("Default", style.primary_colour))
    for speaker, colour in sorted(style.speaker_colours.items()):
        lines.append(style_line(_speaker_style(speaker), colour))

    lines += [
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]

    for cue in sorted(track.cues, key=lambda c: c.start):
        name = (
            _speaker_style(cue.speaker)
            if cue.speaker and cue.speaker in style.speaker_colours
            else "Default"
        )
        text = (
            _karaoke(cue, style)
            if style.highlight_active_word and cue.words
            else escape_text(cue.text)
        )
        lines.append(
            f"Dialogue: 0,{format_timestamp(cue.start)},{format_timestamp(cue.end)},"
            f"{name},,0,0,0,,{text}"
        )

    return "\n".join(lines) + "\n"


def _karaoke(cue, style: CaptionStyle) -> str:
    """Per-word highlight using ASS ``\\k`` timing.

    ``\\kf`` fills the word progressively over its duration; the secondary
    colour in the style is what it fills from.

    The style's case is applied here too. This path renders the individual
    words rather than the cue's already-cased text, so without doing so an
    uppercase caption style would silently render as spoken whenever
    highlighting was enabled.
    """
    from social_video.captions.chunk import apply_case

    parts: list[str] = []
    cursor = cue.start
    for word in cue.words:
        lead = max(0.0, word.start - cursor)
        if lead > 0.005:
            parts.append(f"{{\\k{round(lead * 100)}}}")
        duration = max(0.01, word.end - word.start)
        text = escape_text(apply_case(word.text, style.case))
        parts.append(f"{{\\kf{round(duration * 100)}}}{text} ")
        cursor = word.end
    return "".join(parts).rstrip()


def _speaker_style(speaker: str | None) -> str:
    """ASS style names may not contain commas."""
    return "S_" + (speaker or "unknown").replace(",", "_").replace(" ", "_")


def write_ass(
    track: CaptionTrack,
    style: CaptionStyle,
    path: Path,
    *,
    width: int,
    height: int,
    font_name: str | None = None,
) -> Path:
    """Write an ASS file as UTF-8, which is the only encoding libass accepts."""
    path.parent.mkdir(parents=True, exist_ok=True)
    document = render_ass(track, style, width=width, height=height, font_name=font_name)
    path.write_text(document, encoding="utf-8")
    return path
